acc/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),
]

tpro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from tpro import views as local_views
from post import views as app_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('acc.urls',namespace='accounts')),
    path('proyecto/', local_views.primera_pagina),
    path('prueba/', local_views.debugger_primario),
    #path('posts/', app_views.posts_viewer),
    url(r'^home/$', views.home, name="home"),
    path('login/', app_views.login_view),
]



urlpatterns += staticfiles_urlpatterns()

acc/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models

# Create your models here.

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.

def signup_view(request):
    if request.method =='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            
            login(request, user)

            return redirect('home')
    else:
        form=UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})
    #usuario1 guatemala123@@

def login_view(request):
    if request.method =='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            
            user = form.get_user()
            login(request, user)
            return redirect('home')

    else:

        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method =='POST':
        logout(request)
        return redirect('home')

post/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.

'''
posts_listener = [
{
    'title': 'proyectos',
    'user': {
        'name': 'Clase 10/09/2019'
        'picture': 'https://cdn1.iconfinder.com/data/icons/user-pictures/100/unknown-512.png'
    }
    'cuerpo': 'Esta clase trata de mostrar una pagina posts',

}
]
'''

#def post_viewer(request):
#    return render(request,'index.html')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm()
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', { 'form': form})

tpro/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from datetime import datetime
import json

def primera_pagina(request):
    hora = datetime.now().strftime('%b %d th, %Y - %H:%M hrs')
    return HttpResponse('Esta es nuestra primera pagina en django. y la hora es {hora}'.format(hora=hora))

def debugger_primario(request):
    numero = request.GET['numeros']
    numero= numero.split(',')
    numero = list(map(int, numero))
    numero.sort()
    #import pdb; pdb.set_trace()
    salida = {"Estado": "OK", "Numeros": numero, "Mensaje": "Numeros en JSON y ordenados de menor a Mayor"}
    return HttpResponse(json.dumps(salida, indent=4))  



def home(request):
    return render(request,'home.html')

acc/templates/accounts/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="uft-8">
        <title>Home Page</title>
    </head>
    <body>
        <h1>Bienvenido</h1>

    </body>

</html>

acc/templates/accounts/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="uft-8">
        <title>Login</title>
    </head>
    <body>
        <h1>Log in to Proyectos</h1>
        <form class="site-form" action="accounts/login/" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Login">
        </form>  
    
    </body>

</html>

acc/templates/accounts/signup.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="uft-8">
        <title>Login</title>
    </head>
    <body>
        <h1>Crear Usuario</h1>
        <form  action="/accounts/signup/" method="post">
            
            {{ form }}
    
            <input type="submit" value="Signup">
            {% csrf_token %}    
        </form>
    </body>

</html>

post/templates/login.html
<html>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="uft-8">
        <title>Login</title>
        <link rel="stylesheet" href="css\bootstrap.min.css">
    </head>
    <body class="h-100">
        <div class="container h-100">
            <div class="row h-100 justify-content-center align-items-center">
                <div class="col-sm-12 col-md-5 col-lg-5pt-2 pl-5 pr-5 pb-5" id="auth-container">
                    <img src="img/image.png" class="img-fluid rounded mx-auto d-block pb-4" style="max-width:60%;">
                    <form method="POST" action="login">
                            {% csrf_token %}
                            <input type="text" placeholder="Username" name="username" />
                            <input type="password" placeholder="Password" name="password" />
                            <button type="submit">Login</button>
                    </form>
    </div> 
    </div>
    </div> 
    </body>

</html>

tpro/templates/home.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Inicio</title>
        
    </head>
    <body>
        <header class="wrapper">
            <nav>
                <ul>
                    <li>
                        <form class = "logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>                                
                        </form>                                       
                    </li>                                  
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>